
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class SignalReceiver {

    public static void main(String[] args) {

        //this needs to be included in app-linux-rp-controller, app-linux-sp-controller
        //just after main
        DebugSignalHandler.listenTo("USR2");

        //this is not necessary - just to make sure the program keeps running long enough to get
        //the signal
        while (true) {
            try {
                Thread.sleep(1000);
            }
            catch(InterruptedException e) {
                //
            }
        }
    }
}
